# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# first terms in the sequence
n1 = 1
n2 = 2
# define Fibonacci sequence
fibo = function(n) {
  if(n == 1) {
    return (n1)
  } else if (n == 2) {
    return (n2)
  } else {fibo(n-1)+fibo(n-2)}
}
#find how long fibo sequence is
find_greatest <- function () {
  counter = 1
  actual = 1
  limit = 4000000
  while (actual <= limit) {
    counter <- counter + 1
    actual <- fibo(counter)
  } 
  return (c(counter, actual))
}
# results: after 33 term fibo number is too big - let's check it
print(fibo(33)) # = 5702887 - too big!
print(fibo(32)) # = 3524578, last fibo number we can add.
#getting a list of all fibo numbers in this sequence
results_full <- list()
for (n in c(1:32)) {
  results_full[n] <- fibo(n)
}
#filtering out the numbers that are not even
results_even <- list()
for (n in c(1:32)) {
  if (as.numeric(results_full[n]) %% 2 == 0) {
    results_even[n] <- results_full[n]
  } else {
    results_even[n] <- 0
  }
}
#getting results
res = 0
for (n in c(1:32)) {
  res = res + as.numeric(results_even[n])
}
print(res) # final results = [1] 4613732, hurray!