'''
 Even Fibonacci numbers 
 Problem 2 # Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be: # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

#define fibo function
def fibo(n):
    if n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        return (fibo(n-1)+fibo(n-2))
    
# results
sum = 0 
i = 2 
while sum < 4000000:
    if(fibo(i)%2 == 0):
        sum += fibo(i) 
    i += 1 
    print(sum)
        